name: CI/CD

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
		    with: 
          ref: dev

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.14.2

      - name: Install dependencies
        run: npm install

      - name: Test lint
        run: npm run lint

      - name: Build project
        run: npm run build
